### ISSUE TITLE
travis-ci deploy update

### ISSUE THREAD

**Issue by luizcarloscf** [labviros/is-wire-py#16]
Ubuntu Xenial 16.04 is the new default on travis-ci build environment. Repositories without an explicit dist: YAML key in their .travis.yml file will be routed to Xenial instead of Trusty. See more on [travis-ci blog](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment).

And sudo has no effect anymore.

**current deploy**

https://github.com/labviros/is-wire-py/blob/d83d8d7cb3904eaa2de240c47d5eaca467c81845/.travis.yml#L1-L3

**xenial**

RabbitMQ is not pre-installed on Xenial. [Xenial databases and services](https://docs.travis-ci.com/user/reference/xenial#databases-and-services).

Solution:

 
```yml
dist: xenial
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - rabbitmq
```

**trusty**

On Trusty, RabbitMQ is pre-installed. [Trusty databases and services](https://docs.travis-ci.com/user/reference/trusty#databases-and-services).

Solution:

```yml
dist: trusty
services:
- rabbitmq
```
For more info, checkout the [travis-ci docs about RabbitMQ](https://docs.travis-ci.com/user/database-setup/#rabbitmq).

All the old builds were made using ubuntu trusty, so keep using it or pull request with ubuntu xenial build environment?
